Adds Docker Compose and Poetry toml and lock files
sul-dlss/folio-airflow pull request #1
Opened 2021-11-17 23:29 UTC by jermnelson

Enable better dependency management with [Poetry](https://python-poetry.org/). Adds new `docker-compose.yaml` for running an Airflow environment.

2021-11-18 18:02 UTC, jgreben requested changes
In the readme maybe a copy/paste typo?

2021-11-18 18:02 UTC, jgreben commented on README.md
> +1. Clone repository `git clone https://github.com/LD4P/ils-middleware`
Should this be `sul-dlss/folio-airflow`?

2021-11-30 21:30 UTC, jgreben commented
@jermnelson please check the PR when you get a chance. Thanks!

2021-11-30 22:12 UTC, jermnelson commented on README.md
> +1. Clone repository `git clone https://github.com/LD4P/ils-middleware`
Good catch! Just fixed with latest commit.

2021-11-30 23:22 UTC, jgreben approved these changes

2021-11-30 23:22 UTC, merged