Switch to use HoldingsCsvTransformer for Holdings
sul-dlss/folio-airflow pull request #31
Opened 2022-02-04 02:47 UTC by jermnelson

Generates a TSV file for Holdings migration based on the bib records' 999 fields.

FIXES #29 

TODO:
- [ ] Create a general ERR location if library ERR holding locations don't exist, need to update https://github.com/sul-dlss/folio_migration/blob/sul-999-bib-locations/mapping_files/locations.tsv#L215

2022-02-10 17:36 UTC, jgreben requested changes

2022-02-10 17:36 UTC, jgreben commented on dags/bib_records.py
> +    for path in pathlib.Path(f"{airflow}symphony/").glob("*.*rc"):
Maybe nit-picky, but can we put the slash here and remove from line 36?

2022-02-10 17:36 UTC, jgreben commented on dags/folio_post.py
> +def _generate_holdings_tsv(holdings_csv: csv.DictWriter,
tsv?

2022-02-10 19:23 UTC, jermnelson commented
> Is it csv or tsv? Can the naming be consistent everywhere?

Done, in latest commit.

2022-02-11 20:34 UTC, jgreben requested changes

2022-02-11 20:34 UTC, jgreben commented on dags/folio_post.py
> +    airflow = "/opt/airflow/"
`/opt/airflow`

2022-02-11 20:34 UTC, jgreben commented on dags/folio_post.py
> +    holdings_tsv_file = open(f"{airflow}migration/data/items/sul-holdings.tsv", "w+")  # noqa
`{airflow}/migration/`...

2022-02-11 21:40 UTC, jgreben approved these changes

2022-02-11 21:40 UTC, merged